version: '3'

services:
  traefik:
    image: traefik:latest
    command: --docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json:/acme.json
    networks:
      - prod
    restart: on-failure
    container_name: traefik

  portainer:
    image: portainer/portainer:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - prod
    labels:
      - traefik.frontend.rule=Host:portainer.tymclyps.de
    restart: on-failure
    container_name: portainer

volumes:
  portainer_data:

networks:
  prod:
