defaultEntryPoints = ["http", "https"]

[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]

[acme]
email = "mail@divoisia.de"
storage = "acme.json"
caServer = "https://acme-v01.api.letsencrypt.org/directory"
entryPoint = "https"
[acme.httpChallenge]
entryPoint = "http"

[[acme.domains]]
main = "viduct.de"
sans = ["www.divoisia.com", "divoisia.com", "www.divoisia.de", "divoisia.de", "matomo.viduct.de","portainer.viduct.de","wiki.divoisia.de","wikivoisia.divoisia.de","download.divoisia.de","cloud.divoisia.de"]

[file]
watch = true
